---
- name: Deploy Kubernetes resources from Git repository
  hosts: ubuntuserver
  gather_facts: false
  become: true
  tasks:
    - name: Apply Kubernetes resources
      command: kubectl apply -f /home/ubuntu/jenkinsslave/workspace/deployment_code/deployment_files/service.yaml && kubectl apply -f /home/ubuntu/jenkinsslave/workspace/deployment_code/deployment_files/pod.yaml && kubectl apply -f /home/ubuntu/jenkinsslave/workspace/deployment_code/deployment_files/deployment.yaml
