---
- name: Deploy Kubernetes resources from Git repository
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Apply Kubernetes service
      command: kubectl apply -f /home/ubuntu/jenkinsslave/workspace/deployment_code/deployment_files/service.yaml

    - name: Apply Kubernetes deployment
      command: kubectl apply -f /home/ubuntu/jenkinsslave/workspace/deployment_code/deployment_files/deployment.yaml

    - name: Apply Kubernetes Pod
      command: kubectl apply -f /home/ubuntu/jenkinsslave/workspace/deployment_code/deployment_files/pod.yaml
