- name: Deploy resources to EKS cluster
  hosts: localhost
  become: true
  vars:
    service: my-service-name
    pod: my-pod-name
    deployment: my-deployment-name
  tasks:
    - name: Include service YAML
      include_vars:
        file: service.yaml

    - name: Include pod YAML
      include_vars:
        file: pod.yaml

    - name: Include deployment YAML
      include_vars:
        file: deployment.yaml

    - name: Apply service configuration
      kubernetes.core.k8s:
        state: present
        definition: "{{ service }}"
        name: "{{ service.metadata.name }}"
        kubeconfig: /home/ubuntu/.kube/config

    - name: Apply pod configuration
      kubernetes.core.k8s:
        state: present
        definition: "{{ pod }}"
        name: "{{ pod.metadata.name }}"
        kubeconfig: /home/ubuntu/.kube/config

    - name: Apply deployment configuration
      kubernetes.core.k8s:
        state: present
        definition: "{{ deployment }}"
        name: "{{ deployment.metadata.name }}"
        kubeconfig: /home/ubuntu/.kube/config
