---
- name: Deploy on EKS Kubernetes cluster
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Apply eks cluster
      command: aws eks update-kubeconfig --name pgpxyzfinal --region us-east-1
      
    - name: Modify Deployment manifest with dynamic image tag
      replace:
        path: deployment.yaml
        regexp: '(image: 147217712372.dkr.ecr.us-east-1.amazonaws.com/pgpxyz:)(.*)$'
        replace: '\g<1>{{ image_tag }}'

    - name: Apply Deployment manifest
      k8s:
        state: present
        definition: "{{ lookup('file', 'deployment.yaml') }}"
