---
- name: Deploy to AWS EKS cluster
  hosts: localhost
  become: true
  tasks:s
    - name: Include service YAML
      include_vars:
        file: service.yaml

    - name: Include pod YAML
      include_vars:
        file: pod.yaml

    - name: Include deployment YAML
      include_vars:
        file: deployment.yaml

    - name: Apply Service
      shell: /home/ubuntu/kubectl apply -f service.yaml --validate=false

    - name: Apply Pod
      shell: /home/ubuntu/kubectl apply -f pod.yaml --validate=false

    - name: Apply Deployment
      shell: /home/ubuntu/kubectl apply -f deployment.yaml --validate=false
