- name: Check host connectivity
  hosts: aws 
  gather_facts: false
  become: true
  tasks:
    - debug: msg="Ansible is working"

    - name: Clone Git repository
      git:
        repo: https://github.com/dinakara079/naveenfinalpgp.git
        dest: /tmp/pgpfinal
        version: master

    - name: Apply Service
      command: kubectl apply -f /tmp/pgpfinal/deployment_files/service.yaml --validate=false
      register: kubectl_result
      ignore_errors: true  # Ignore errors to handle the case when validation fails

    - name: Apply Pod
      command: kubectl apply -f /tmp/pgpfinal/deployment_files/pod.yaml

    - name: Apply Deployment
      command: kubectl apply -f /tmp/pgpfinal/deployment_files/deployment.yaml