- name: Check host connectivity
  hosts: aws 
  gather_facts: false
  become: true
  tasks:
    - debug: msg="Ansible is working"

    - name: Clone Git repository
      git:
        repo: https://github.com/dinakara079/naveenfinalpgp.git
        dest: /tmp/pgpfinal
        version: master

    - name: Apply Kubernetes resources
      command: kubectl apply -f /tmp/pgpfinal/deployment_files/service.yaml && kubectl apply -f /tmp/pgpfinal/deployment_files/pod.yaml && kubectl apply -f /tmp/pgpfinal/deployment_files/deployment.yaml