---
- name: Deploy to AWS EKS cluster
  hosts: localhost
  become: true
  tasks:
    - name: Include service YAML
      include_vars:
        file: ./deployment_files/service.yaml

    - name: Include pod YAML
      include_vars:
        file: ./deployment_files/pod.yaml

    - name: Include deployment YAML
      include_vars:
        file: ./deployment_files/deployment.yaml

    - name: Apply Service
      shell: kubectl apply -f ./deployment_files/service.yaml

    - name: Apply Pod
      shell: kubectl apply -f ./deployment_files/pod.yaml

    - name: Apply Deployment
      shell: kubectl apply -f ./deployment_files/deployment.yaml

