apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgpapp
  namespace: pgpapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgpapp
  template:
    metadata:
      labels:
        app: pgpapp
    spec:
      containers:
        - name: pgpapp
          image: 147217712372.dkr.ecr.us-east-1.amazonaws.com/pgpxyz:{{ image_tag }}
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pgpapp
  namespace: pgpapp
spec:
  selector:
    app: pgpapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
